version: '3.8'

services:
  analysis_portal:
    build: .
    container_name: analysis_portal
    ports:
      - "8001:8001"
    volumes:
      - ./images:/usr/share/nginx/html/images
      - ./html:/usr/share/nginx/html:ro
    restart: always
